name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  self-test:
    name: Self test
    runs-on: ubuntu-latest
    steps:
      - uses: rizary/action-cli@v0.4.0
      - run: cat $GITHUB_EVENT_PATH
      - shell: bash
        run: |
          planCommentsURL=$(jq -r .pull_request.comments_url < "$GITHUB_EVENT_PATH")
          echo "plan: info: commenting on the pull request"
          echo ${planCommentsURL}
          echo "after comment"
          curl -s -f -S \
          --url ${planCommentsURL} \
          --header 'authorization: Bearer ${{secrets.ACTION_CLI_EXAMPLE}}' \
          --header 'content-type: application/json, \
          
