name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  self-test:
    name: Self test
    runs-on: ubuntu-latest
    steps:
      - uses: rizary/action-cli@v0.4.0
      - run: action-cli warning --file Cargo.toml --line 2 --col 2 "Ooops"
