name: "CI"
on:
  pull_request:
jobs:
  self-test:
    name: Self test
    runs-on: ubuntu-latest
    steps:
      - uses: rizary/action-cli@v0.4.0
      - run: cat $GITHUB_EVENT_PATH
      - shell: bash
        run: |
          planCommentsURL=$(jq -r .pull_request.comments_url < "$GITHUB_EVENT_PATH")
          echo "plan: info: commenting on the pull request"
          echo ${planCommentsURL}
          echo "Hello world" | \
          curl -s -f -S --data @- \
          --request POST \
          --url ${planCommentsURL} \
          --header 'authorization: Bearer ${{secrets.ACTION_CLI_EXAMPLE}}' \
          --header 'content-type: application/json' > /dev/null
          
